# jdbc.X
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/snowman?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
jdbc.username=username
jdbc.password=password

# hibernate.X
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
# validate | update | create | create-drop
hibernate.hbm2ddl.auto=validate

# Messaging - JMS
jms.brokerUrl=tcp://localhost:61616
